#' Deterministic LLM block constructor
#'
#' Like `new_llm_block()` but uses a deterministic loop instead of tools.
#' The system controls the flow: show data → LLM writes code → system runs →
#' iterate until DONE.
#'
#' @param messages See [shinychat::chat_ui()]
#' @param code Code as generated by the LLM
#' @param ... Forwarded to [blockr.core::new_block()]
#' @inheritParams blockr.core::new_block
#'
#' @return Block inheriting from `llm_block`.
#'
#' @export
new_llm_block_det <- function(class, messages = list(), code = character(),
                               ctor = sys.parent(), ...) {

  if (is_single_user_turn(messages)) {
    messages <- list(
      list(role = "user", content = messages)
    )
  } else if (is_single_turn(messages)) {
    messages <- list(messages)
  } else if (is_empty(messages)) {
    messages <- list()
  }

  cls <- c(class, "llm_block")

  llm_obj <- structure(
    list(
      messages = check_messages(messages),
      code = code
    ),
    class = paste0(cls[1], "_proxy")  # e.g., llm_transform_block_det_proxy
  )

  new_block(
    server = llm_block_server_det(llm_obj),
    ui = llm_block_ui_det(llm_obj),
    class = cls,
    ctor = ctor,
    allow_empty_state = "messages",
    ...
  )
}
