#' LLM block constructor
#'
#' Basic constructor for blocks that inherit from `llm_block`. Intended to be
#' used for more specific block classes such as LLM-based transform or plot
#' blocks.`)
#'
#' @param question LLM prompt
#' @param code Code as generated by the LLM
#' @param explanation Explanation for the generated code
#' @param ... Forwarded to [blockr.core::new_block()]
#' @inheritParams blockr.core::new_block
#'
#' @return All blocks constructed via `new_llm_block()` inherit from
#' `llm_block`.
#'
#' @export
new_llm_block <- function(class, question = "", code = "",
                          explanation = character(),
                          ctor = sys.parent(),
                          ...) {

  cls <- c(class, "llm_block")

  llm_obj <- structure(
    list(question = question, code = code, explanation = explanation),
    class = paste0(cls, "_proxy")
  )

  new_block(
    server = llm_block_server(llm_obj),
    ui = llm_block_ui(llm_obj),
    class = cls,
    ctor = ctor,
    allow_empty_state = "explanation",
    ...
  )
}

#' @param x Proxy LLM block object
#' @rdname new_llm_block
#' @export
result_ptype <- function(x) {
  UseMethod("result_ptype")
}
